add checks for services
18F/identity-give-orchestration pull request #5
Opened 2021-05-27 19:24 UTC by dzaslavskiy

2021-05-27 20:05 UTC, folksgl requested changes
Only thing I worry about with this is that I've seen the elasticsearch instances in cloud.gov take 3hrs to create. We should keep this validation in place in case the service accidentally gets deleted or something. Still good to check but we may still be on our own for validating that it's up before running a deployment.

2021-05-27 20:05 UTC, folksgl commented on .github/workflows/deploy-api.yaml
> +      - name: Ensure Service Available
```suggestion
      - name: Ensure Redis Available
```

2021-05-27 20:05 UTC, folksgl commented on .github/workflows/deploy-api.yaml
> +      - name: Ensure Service Available
```suggestion
      - name: Ensure Postgres Available
```

2021-05-27 20:05 UTC, folksgl commented on .github/workflows/deploy-events.yaml
> +      - name: Ensure Service Available
```suggestion
      - name: Ensure Elasticsearch Available
```

2021-06-22 19:54 UTC, folksgl commented on .github/workflows/deploy-analytics.yaml
> +      - '*'
For "deploy X SK app" we're probably going to want app-specific tags we trigger deployments on, right? Perhaps we post-fix an app identifier to tags? That way we can trigger deployments to test only on `*-analytics` where the tag could be versioned specifically for the analytics code as `v2.4-analytics`. Thoughts?

This feels a bit like an abuse of versioning but as it stands we have a litany of sub-applications here all on their own versions and I can't think of a better way to pin versions where we need to.

2021-06-22 19:54 UTC, folksgl commented on .github/workflows/deploy-analytics.yaml
> +          echo "$SK_SECRETS" | sed 's/^/  /' >> vars.yaml
This could use a clarifying comment as to why the `| sed...` is necessary.

2021-06-22 19:54 UTC, folksgl commented on README.md
> +The github actions workflows provision the services and deploy the applications.
This feels slightly misleading since, as you state below, there is an ordering that needs to be enforced. It looks like its "run the workflows related to the #tasks section above" followed by everything else. If that's the case, then some re-wording to make that more clear is probably in order.

2021-06-22 19:54 UTC, folksgl commented on README.md
> +The api, portal and sdk microservice need public routes.
Is this still accurate?

2021-06-22 20:46 UTC, dzaslavskiy commented on .github/workflows/deploy-analytics.yaml
> +      - '*'
I think a tag only needs to an overall application version that would consist of a set of services each at a specific version. Those service versions are determined by the version files in the repo.

2021-06-23 15:54 UTC, folksgl approved these changes

2021-06-23 16:12 UTC, merged